# Build PCA 
We will build PCA and then compare it to T-SNE and LDA (3 DR methods total)

In [2]:
import numpy as np
np.random.seed(1) # for debugging

In [8]:
# Create dataset
mu_vec1 = np.array([0, 0, 0]) # Sample mean
cov_mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) # Sample covariance

class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20).T # 3x20 matrix
print(class1_sample)

[[ -4.98213564e-01  -1.39662042e+00   6.18539131e-01  -1.30572692e+00
   -2.79308500e+00  -1.04458938e+00   4.29526140e-01  -1.52568032e+00
    1.34048197e-01   2.62467445e-01   8.36004719e-01   8.84908814e-01
   -1.44087602e+00   1.39984394e+00   9.54250872e-02   2.11124755e-01
   -1.11647002e+00  -5.68244809e-02  -8.45080274e-02   7.84770651e-01]
 [ -3.10984978e-01  -8.61316361e-01  -4.43171931e-01  -3.44987210e-01
    1.93752881e+00   2.05117344e+00  -6.06998398e-01   7.95026094e-01
    1.20205486e+00   2.76499305e-01   1.54335911e+00  -8.77281519e-01
    1.23225307e+00  -7.81911683e-01   9.21450069e-01   1.65275673e-02
    8.09271010e-02   4.92336556e-01  -2.97361883e-01  -9.55425262e-01]
 [ -1.89148284e-03   6.74711526e-01   1.81053491e+00  -2.30839743e-01
    3.66332015e-01   5.85662000e-01   1.06222724e-01  -3.74438319e-01
    2.84748111e-01  -7.33271604e-01   7.58805660e-01  -8.67787223e-01
   -2.54179868e-01  -4.37508983e-01   6.07501958e-02   1.77187720e-01
   -1.86578994e-01

In [7]:
mu_vec2 = np.array([1, 1, 1]) # Sample mean
cov_mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) # Sample covariance

class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20).T # 3x20 matrix
print(class1_sample)

[[-0.75439794 -0.29809284  1.13162939 -1.39649634  0.16003707 -2.02220122
   0.23009474 -0.20075807  0.19829972  0.37756379  1.19891788 -0.63873041
  -0.34385368  0.69803203  0.40349164  0.16938243 -0.26621851  0.31515939
   0.35054598 -1.61577235]
 [ 1.25286816  0.48851815  1.51981682 -1.44411381  0.87616892 -0.30620401
   0.76201118  0.18656139  0.11900865  0.12182127  0.18515642  0.42349435
   0.04359686 -0.44712856  0.59357852  0.74055645  0.03261455  0.84616065
  -1.31228341  1.12141771]
 [ 0.51292982 -0.07557171  2.18557541 -0.50446586  0.31563495  0.82797464
  -0.22232814  0.41005165 -0.67066229  1.12948391 -0.37528495  0.07734007
  -0.62000084  1.2245077  -1.09491185 -0.9537006  -1.37311732 -0.85951594
  -0.03869551  0.40890054]]


In [13]:
# Merge the data into 1 bigASS dataset
all_samples = np.concatenate((class1_sample, class2_sample), axis=1)
all_samples

array([[ -4.98213564e-01,  -1.39662042e+00,   6.18539131e-01,
         -1.30572692e+00,  -2.79308500e+00,  -1.04458938e+00,
          4.29526140e-01,  -1.52568032e+00,   1.34048197e-01,
          2.62467445e-01,   8.36004719e-01,   8.84908814e-01,
         -1.44087602e+00,   1.39984394e+00,   9.54250872e-02,
          2.11124755e-01,  -1.11647002e+00,  -5.68244809e-02,
         -8.45080274e-02,   7.84770651e-01,  -2.72558755e-01,
          2.29322588e+00,   1.56276110e+00,   9.26887296e-01,
          2.90465871e+00,  -6.27438341e-01,   1.81095167e+00,
          1.82400562e+00,  -3.31951667e-01,   1.09444416e-01,
          6.73500502e-01,   4.13476061e-01,   1.62336218e+00,
          1.12910158e+00,   2.55880554e+00,   3.44936865e+00,
          2.99601495e-01,   1.20183018e+00,   8.79535428e-01,
          3.34245482e-01],
       [ -3.10984978e-01,  -8.61316361e-01,  -4.43171931e-01,
         -3.44987210e-01,   1.93752881e+00,   2.05117344e+00,
         -6.06998398e-01,   7.95026094e-01,

In [14]:
all_samples.T

array([[ -4.98213564e-01,  -3.10984978e-01,  -1.89148284e-03],
       [ -1.39662042e+00,  -8.61316361e-01,   6.74711526e-01],
       [  6.18539131e-01,  -4.43171931e-01,   1.81053491e+00],
       [ -1.30572692e+00,  -3.44987210e-01,  -2.30839743e-01],
       [ -2.79308500e+00,   1.93752881e+00,   3.66332015e-01],
       [ -1.04458938e+00,   2.05117344e+00,   5.85662000e-01],
       [  4.29526140e-01,  -6.06998398e-01,   1.06222724e-01],
       [ -1.52568032e+00,   7.95026094e-01,  -3.74438319e-01],
       [  1.34048197e-01,   1.20205486e+00,   2.84748111e-01],
       [  2.62467445e-01,   2.76499305e-01,  -7.33271604e-01],
       [  8.36004719e-01,   1.54335911e+00,   7.58805660e-01],
       [  8.84908814e-01,  -8.77281519e-01,  -8.67787223e-01],
       [ -1.44087602e+00,   1.23225307e+00,  -2.54179868e-01],
       [  1.39984394e+00,  -7.81911683e-01,  -4.37508983e-01],
       [  9.54250872e-02,   9.21450069e-01,   6.07501958e-02],
       [  2.11124755e-01,   1.65275673e-02,   1.7718772

In [15]:
# Compute the dimensional mean vector, it will help compute the covariance matrix
mean_x = np.mean(all_samples[0,:])
mean_y = np.mean(all_samples[1,:])
mean_z = np.mean(all_samples[2,:])

mean_vector = np.array(([[mean_x], [mean_y], [mean_z]]))
mean_vector

array([[ 0.42892194],
       [ 0.54264958],
       [ 0.74237807]])

In [20]:
# Compute  covariance-matrix
cov_mat = np.zeros((3, 3))

for i in range(all_samples.shape[1]):
    cov_mat += (all_samples[:,i].reshape(3, 1) - mean_vector).dot((all_samples[:,i].reshape(3,1) - mean_vector).T)
    
print(cov_mat)

[[ 65.45671316   5.56552221  15.76981641]
 [  5.56552221  40.63156831   9.24284598]
 [ 15.76981641   9.24284598  44.00621722]]


In [21]:
# Compute eigenvectors and values
eig_val, eig_vec = np.linalg.eig(cov_mat)
print(eig_val)
print(eig_vec)

[ 76.25350253  42.46100742  31.37998874]
[[-0.83737261 -0.48548384 -0.25122213]
 [-0.25613139  0.75447819 -0.60428419]
 [-0.48291182  0.44166515  0.75612702]]


In [23]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i])
             for i in range(len(eig_val))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
for i in eig_pairs:
    print(i[0])

76.2535025341
42.4610074203
31.3799887374


In [24]:
#k is 2 
matrix_w = np.hstack((eig_pairs[0][1].reshape(3,1),
                      eig_pairs[1][1].reshape(3,1)))
print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.83737261 -0.48548384]
 [-0.25613139  0.75447819]
 [-0.48291182  0.44166515]]


In [25]:
# transform our data
transformed = matrix_w.T.dot(all_samples)
print(transformed)

[[  4.97756825e-01   1.06427567e+00  -1.27876620e+00   1.29321725e+00
    1.66568487e+00   6.65175330e-02  -2.55498292e-01   1.25475246e+00
   -5.57640496e-01   6.35023254e-02  -1.46178639e+00  -9.72343618e-02
    1.01367789e+00  -7.60640590e-01  -3.45255626e-01  -2.66589360e-01
    1.00427464e+00   2.50187939e-01  -5.45916521e-02  -6.95374122e-01
   -8.34113280e-01  -2.33290736e+00  -2.24485335e+00  -1.99082477e+00
   -3.77416428e+00  -5.70875645e-01  -2.32941012e+00  -3.06642521e+00
    7.87044441e-01  -1.48866201e+00  -1.49726138e+00  -1.19143274e+00
   -2.66671387e+00  -2.34145300e+00  -2.32070936e+00  -3.39163898e+00
   -1.05501353e+00  -2.78018531e+00  -5.88745760e-01  -9.88533779e-01]
 [  6.40784860e-03   3.26188808e-01   1.64995874e-01   2.71670123e-01
    2.97961694e+00   2.31336338e+00  -6.19580175e-01   1.17514663e+00
    9.67609258e-01  -2.42671524e-01   1.09370202e+00  -1.47477007e+00
    1.51696770e+00  -1.46276939e+00   6.75717884e-01  -1.17703258e-02
    5.20680443e-01 