In [1]:
import numpy as np

In [2]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [4]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [5]:
print(y )

[[0]
 [1]
 [1]
 [0]]


In [6]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [8]:
print(syn0)

[[-0.7251174   0.13751652 -0.48678724 -0.53289159]
 [ 0.61629985 -0.19224305 -0.24800152  0.47489293]
 [ 0.3229962  -0.16955605 -0.85045883 -0.99114887]]


In [9]:
print(syn1)

[[-0.09020247]
 [ 0.18007148]
 [ 0.13737232]
 [-0.99848089]]


In [10]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [13]:
#Step 3 Train Model

for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x # Input layer
    l1 = nonlin(np.dot(l0, syn0)) # Hidden layer
    l2 = nonlin(np.dot(l1, syn1)) # Output layer
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
    
    #in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta= l1_error * nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.501315656932
Error:0.00887062519512
Error:0.00595714318481
Error:0.00475827273762
Error:0.00406717799867
Error:0.00360512201893
